### ISSUE TITLE
Evaluate lux components in StyleGuidist

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lux#432]
- [x] Get a working instance of StyleGuidist running -- done at https://github.com/pulibrary/lux-styleguidist
- [x] Copy TextStyle and MediaImage into StyleGuidist
- [x] Figure out how to use sass variables (the variables are in slack)
- [x] Figure out how to use sass mixins (the TextStyle.vue component relies on two mixins)
- [x] Confirm that our documentation still generates
- [x] See if the TextStyle and MediaImage tests still run in StyleGuidist/Vue3
- [x] Copy Card
- [x] Copy Gallery into StyleGuidist
- [x] Implement State management in the Gallery
- [x] Implement Vue-draggable in the Gallery (to confirm that we can use 3rd-party plugins in the new setup)
- [x] Confirm that in the gallery, you can select, deselect, and re-order gallery items using drag-and-drop
- [x] Check the deployment, packaging, and versioning for releasing a new version
- [x] Try using the lux-styleguidist repo in a local development environment of an application that currently uses lux.  Make sure there are no issues.

**Comment by sdellis** [comment]
Note:

1. Figure out how to integrate sass
2. Convert LUX functional components back to original form
